# Site settings
title: Stephen Herko
email: hello@stephenherko.com
description: "As a UX Designer, I believe developing a deep understanding of human and social behavior is the key to good product design."
tagline: "User Experience Designer Solving Problems for Humans"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://stephenherko.com" # the base hostname & protocol for your site
twitter: https://twitter.com/stephenherko
github: https://github.com/stephenherko
linkedin: https://linkedin.com/in/stephenherko
permalink: /:title

# Build settings
markdown: kramdown
sass:
  style: compressed
